defaults:
  - bioclip

gnn:
  residue_embedding_dim: 1024
  positional_encoding_dimension: 1024

  gnn_number_layers: 3
  shared_layers: false
  stop_aggregation_gradient: true

  gnn_layer:
    layer_cls: "GATLayer"
    num_intermediate_factor: 4
    dropout_rate: 0.2
    hidden_dimension: 1024
    num_heads: 4
    key_size: 128
    value_size: 128 # default in haiku is key_size
    output_size: 1024 # default in haiku is num_heads * key_size



dimension_multimodal_space: 1024

aggregation_attention:
  num_heads: 4
  key_size: 128
  value_size: 256


